project:
  type: website
preview:
    port: 4200
    browser: true
website:
  title: "The Bruna Lab"
  site-url: "https://brunalab.org/"
  repo-url: "https://github.com/BrunaLab/bruna-lab-website"
  favicon: images/bruna-logo-bird.png
  open-graph: true
  google-analytics: "G-VJ8YNDL9Z6"
  twitter-card: true
  back-to-top-navigation: true
  page-navigation: false
  search: true
  # body-footer: 'TEST'
  page-footer: 
    background: "#FFFFFF"
    # left: '[![](/images/bruna-logo-full.png){fig-alt="brunalab logo" height=110px}](https://tropicos.netlify.app/)'
    left: '[![](/images/Vertical_Logo_Reversed-RGB_Raster-BLUE2.png){fig-alt="UF logo" height=110px}](https://www.ufl.edu/)'
    # center: Made by Emilio M. Bruna with <br> {{< fa brands r-project fa-2xs >}} and 
    #   [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=105px}](https://quarto.org/) 
    right: Made with {{< fa brands r-project size=2x >}} <br>  
      and [![](https://quarto.org/quarto.png){fig-alt="Quarto" height=20px}](https://quarto.org/) <br>
    
      # - icon: github color: fill='#465672' {fig-alt="Quarto" width=105px}
      #   href: https://github.com/BrunaLab/QuartoBrunaWebsite
      # 
    
  navbar:
    tools:
      # - icon: twitter
      #   href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/BrunaLab/bruna-lab-website
          - text: Suggest a change
            href:  https://github.com/BrunaLab/bruna-lab-website/issues
    search: true
    title: false
    pinned: true
    background: "#FFFFFF"
    # logo: images/bruna-logo-bird.png
    logo: images/bruna-logo-full.png
    logo-alt: "Bruna Lab"
    right:
      - text: Lab Members
        menu:
        - people/embruna/index.qmd
      # - text: lab members
        - people/index.qmd
        - people/prospectives.qmd
      - text: projects
        href: projects/index.qmd
      - text: publications
        href: publications/index.qmd
      - text: courses
        href: courses/index.qmd
      - text: Contact
        href: contact.qmd
format:
  html:
    theme:
      # dark: lux
      light: [lux, styles/custom.scss]
    fontcolor: black
    fontsize: x-large
    mainfont: Nunito Sans
    toc: true
    link-external-newwindow: true
    date-format: "MMM YYYY"
    smooth-scroll: true
    resources:
      - images
# filters:
#   - auto-dark
lightbox: true
execute:
  freeze: auto
