---
title: UF Campus Tree Guide
author: R package build
date: '2022-01-16'
slug: uf-campus-tree-guide
categories:
  - Teaching
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2022-01-16T20:59:23-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

#### THE CODE FOR THIS APP IS AVAILABLE FOR NON-COMMERCIAL USE AT [GITHUB](https://github.com/embruna/UF-tree-guide-for-smartphones) OR FROM EMILIO BRUNA VIA [EMAIL](embruna@ufl.edu).

Students in my graduate course in plant-animal interactions developed a smart phone application designed to teach undergraduate ecology students about plant diversity and plant-animal interactions. It is also a way for the general public to explore the remarkable biodiversity on the UF campus. It maps the locations on the UF campus of over 35 species native to the southeastern US, provides pictures of their fruits, flowers, and other key features, and provides information on the interactions of these trees with different species of animals.

### Application Name: UF Campus Tree Guide
Application Description: This application teaches users about the tree species that can be found on the campus of the University of Florida in Gainesville.Â  It maps the locations on the UF campus of over 35 species native to the southeastern US, provides pictures of their fruits, flowers, and other key features, and provides information on the interactions of these trees with different species of animals.
Requirements: compatible with Android v1.0 and higher.

**Current version:** 1.0.0  
**Size:** 1.4 M  
**Price:** Free  
**Copyright:** Emilio M. Bruna, University of Florida  
**Keywords:** University, Florida, UF, trees, guide, flora, botany, biodiversity  

**Development Team:** Supervisor: Emilio Bruna. Content and Design: Oscar Gonzalez, Shelly Johnson, Anthony Lau, Fabiane Mundim, Matthew Palumbo, Jennifer Ulrich, Amy Washuta, Andrea Wolf. Programmer: Subramaniam Arunachalam (programmer).  
